ECommercePlatform:
  SoftwareSystems:
    ProductService:
      Containers:
        Api:
          Interfaces:
            GetProducts:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Database.Interfaces.SelectProducts
            CreateProduct:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Database.Interfaces.InsertProduct
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Messaging.Interfaces.SendProductCreatedEvent
            UpdateProduct:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Database.Interfaces.UpdateProduct
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Messaging.Interfaces.SendProductUpdatedEvent
            DeleteProduct:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Database.Interfaces.DeleteProduct
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Messaging.Interfaces.SendProductDeletedEvent
        Database:
          Interfaces:
            SelectProducts: {}
            InsertProduct: {}
            UpdateProduct: {}
            DeleteProduct: {}
        Messaging:
          Interfaces:
            SendProductCreatedEvent: {}
            SendProductUpdatedEvent: {}
            SendProductDeletedEvent: {}
            ReceiveProductCreatedEvent: {}
            ReceiveProductUpdatedEvent: {}
            ReceiveProductDeletedEvent: {}
        MessageHandler:
          Interfaces:
            HandleProductCreatedEvent:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Messaging.Interfaces.ReceiveProductCreatedEvent
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.WMS.Interfaces.CreateProduct
            HandleProductUpdatedEvent:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Messaging.Interfaces.ReceiveProductUpdatedEvent
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.WMS.Interfaces.UpdateProduct
            HandleProductDeletedEvent:
              Flow:
                Flows:
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.ProductService.Containers.Messaging.Interfaces.ReceiveProductDeletedEvent
                - Type: Use
                  Expression: ECommercePlatform.SoftwareSystems.WMS.Interfaces.DeleteProduct